services:
  dotnet-1:
    build: ./dotnet
    environment:
      - NAME=Fili
  dotnet-2:
    build: ./dotnet
    environment:
      - NAME=Kili
  nginx:
    image: nginx
    volumes:
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
